import type { ScenarioResult } from "./engine";
import { COMPANY } from "./company";

export interface ReportMeta {
  siteAreaM2: number;
  frontageM: number;
  roadWidthM: number;
  density: string;
  programType: string;
  parcelSource?: "map sketch" | "manual entry" | "saved parcel";
  vertexCount?: number;
}

function reportRef(meta: ReportMeta): string {
  const d = new Date();
  const stamp = d.toISOString().slice(0, 10).replace(/-/g, "");
  return `AG-${stamp}-${meta.siteAreaM2}`;
}

function fmtDate(d = new Date()) {
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

export function buildReportText(scenarios: ScenarioResult[], meta: ReportMeta): string {
  const ref = reportRef(meta);
  const lines: string[] = [];

  lines.push("═".repeat(72));
  lines.push(COMPANY.legalName.toUpperCase());
  lines.push(COMPANY.serviceName);
  lines.push(COMPANY.tagline);
  lines.push("═".repeat(72));
  lines.push("");
  lines.push("DEVELOPMENT CAPACITY ASSESSMENT REPORT");
  lines.push(`Report reference: ${ref}`);
  lines.push(`Generated: ${fmtDate()}`);
  lines.push("");
  lines.push("— SERVICE PROVIDER —");
  lines.push(`Company:     ${COMPANY.legalName}`);
  lines.push(`Service:     ${COMPANY.serviceName}`);
  lines.push(`Website:     ${COMPANY.website}`);
  lines.push(`Email:       ${COMPANY.email}`);
  lines.push(`Telephone:   ${COMPANY.phoneDisplay}`);
  lines.push("");
  lines.push("— PARCEL SUMMARY —");
  lines.push(`Site area:        ${meta.siteAreaM2.toLocaleString()} m²`);
  lines.push(`Frontage:         ${meta.frontageM} m`);
  lines.push(`Road width:       ${meta.roadWidthM} m`);
  lines.push(`Density tier:     ${meta.density}`);
  lines.push(`Program type:     ${meta.programType.replace("_", " ")}`);
  if (meta.parcelSource) lines.push(`Input source:     ${meta.parcelSource}${meta.vertexCount ? ` (${meta.vertexCount} vertices)` : ""}`);
  lines.push(`Regulatory basis: ${COMPANY.jurisdiction}`);
  lines.push("");

  scenarios.forEach((s) => {
    lines.push("─".repeat(72));
    lines.push(`SCENARIO: ${s.scenarioLabel.toUpperCase()}`);
    lines.push("─".repeat(72));
    lines.push(`FAR applied:           ${s.far.value}  [${s.far.confidence}]`);
    if (s.far.note) lines.push(`  Note: ${s.far.note}`);
    lines.push(`Height category:       ${s.heightCategory.label}  [FACT]`);
    lines.push(`Floors:                ${s.floors}  [ESTIMATE]`);
    lines.push(`Building height:       ${s.heightM} m  [ESTIMATE]`);
    lines.push(`Footprint:             ${s.footprintM2} m²  (governing: ${s.governingConstraint})`);
    lines.push(`Achieved GFA:          ${s.achievedGFA} m² of ${s.maxRegulatedGFA} m² regulated ceiling`);
    lines.push(`Regulation utilisation: ${s.regulationUtilisationPct}%`);
    lines.push(`Open space:            ${s.openSpaceM2} m² (${s.openSpacePct}%)`);
    lines.push(`Estimated units:       ${s.units}  [ESTIMATE]`);
    lines.push(`Parking required:      ${s.parking.total} spaces  [ESTIMATE]`);
    lines.push(`Compliance status:     ${s.complianceLevel.toUpperCase()}`);
    if (s.flags.length) {
      lines.push("Compliance flags:");
      s.flags.forEach((f) => lines.push(`  • [${f.level.toUpperCase()}] ${f.message}`));
    }
    lines.push("");
  });

  lines.push("═".repeat(72));
  lines.push("DISCLAIMER");
  lines.push("═".repeat(72));
  lines.push(
    "This report is generated by the AlphaGRID regulation engine for screening and planning assistance purposes only. " +
      "Figures tagged ESTIMATE or INTERPRETED carry stated assumptions. Confirm all capacity, setback, and height " +
      "requirements against the current gazetted planning instrument before any transaction, design commitment, or " +
      "financial decision. AlphaGRID (Pvt.) Ltd accepts no liability for reliance on this document without independent verification."
  );
  lines.push("");
  lines.push(`${COMPANY.legalName} · ${COMPANY.website} · ${COMPANY.email}`);

  return lines.join("\n");
}

export function buildReportHtml(scenarios: ScenarioResult[], meta: ReportMeta): string {
  const ref = reportRef(meta);
  const scenarioRows = scenarios
    .map(
      (s) => `
    <section class="scenario">
      <h2>${s.scenarioLabel}</h2>
      <div class="grid">
        <div class="metric"><span class="label">FAR applied</span><span class="value">${s.far.value}</span><span class="tag">${s.far.confidence}</span></div>
        <div class="metric"><span class="label">Height category</span><span class="value">${s.heightCategory.label}</span><span class="tag">FACT</span></div>
        <div class="metric"><span class="label">Floors</span><span class="value">${s.floors}</span><span class="tag">ESTIMATE</span></div>
        <div class="metric"><span class="label">Building height</span><span class="value">${s.heightM} m</span><span class="tag">ESTIMATE</span></div>
        <div class="metric"><span class="label">Footprint</span><span class="value">${s.footprintM2} m²</span><span class="tag">${s.governingConstraint}</span></div>
        <div class="metric"><span class="label">Achieved GFA</span><span class="value">${s.achievedGFA} m²</span><span class="tag">of ${s.maxRegulatedGFA} m²</span></div>
        <div class="metric"><span class="label">Open space</span><span class="value">${s.openSpaceM2} m²</span><span class="tag">${s.openSpacePct}%</span></div>
        <div class="metric"><span class="label">Est. units</span><span class="value">${s.units}</span><span class="tag">ESTIMATE</span></div>
        <div class="metric"><span class="label">Parking</span><span class="value">${s.parking.total}</span><span class="tag">spaces</span></div>
        <div class="metric"><span class="label">Compliance</span><span class="value status-${s.complianceLevel}">${s.complianceLevel.toUpperCase()}</span></div>
      </div>
      ${
        s.flags.length
          ? `<ul class="flags">${s.flags.map((f) => `<li class="${f.level}"><strong>${f.level.toUpperCase()}</strong> ${f.message}</li>`).join("")}</ul>`
          : ""
      }
    </section>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>AlphaGRID Report ${ref}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "Segoe UI", system-ui, sans-serif; color: #0c1418; background: #f5f6f4; padding: 40px 24px; line-height: 1.5; }
    .page { max-width: 820px; margin: 0 auto; background: #fff; border: 1px solid #d8ded9; border-radius: 12px; overflow: hidden; box-shadow: 0 8px 32px rgba(12,20,24,.08); }
    .header { background: linear-gradient(135deg, #0f6f66 0%, #0a564f 100%); color: #fff; padding: 36px 40px; }
    .header h1 { font-size: 1.5rem; font-weight: 800; letter-spacing: -0.02em; }
    .header .service { font-size: .95rem; opacity: .92; margin-top: 4px; }
    .header .tagline { font-size: .8rem; opacity: .75; margin-top: 8px; }
    .meta-bar { display: flex; flex-wrap: wrap; gap: 24px; padding: 20px 40px; background: #eef1ef; border-bottom: 1px solid #d8ded9; font-size: .82rem; }
    .meta-bar strong { display: block; color: #6a7672; font-size: .7rem; text-transform: uppercase; letter-spacing: .06em; margin-bottom: 2px; }
    .body { padding: 32px 40px 40px; }
    h2 { font-size: 1rem; color: #0f6f66; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #e4f1ee; }
    .parcel-table { width: 100%; border-collapse: collapse; margin-bottom: 32px; font-size: .88rem; }
    .parcel-table td { padding: 10px 14px; border-bottom: 1px solid #eef1ef; }
    .parcel-table td:first-child { color: #6a7672; width: 38%; font-weight: 500; }
    .scenario { margin-bottom: 28px; page-break-inside: avoid; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
    .metric { background: #f7f9f8; border: 1px solid #eef1ef; border-radius: 8px; padding: 12px 14px; }
    .metric .label { display: block; font-size: .72rem; color: #6a7672; text-transform: uppercase; letter-spacing: .05em; }
    .metric .value { display: block; font-size: 1.15rem; font-weight: 700; margin-top: 2px; font-variant-numeric: tabular-nums; }
    .metric .tag { font-size: .68rem; color: #0f6f66; font-weight: 600; }
    .status-green { color: #277a4c; }
    .status-amber { color: #9a5f16; }
    .status-red { color: #a83832; }
    .flags { margin-top: 12px; padding-left: 18px; font-size: .82rem; }
    .flags .amber { color: #9a5f16; }
    .flags .red { color: #a83832; }
    .disclaimer { margin-top: 32px; padding: 20px; background: #faf0dc; border-radius: 8px; font-size: .78rem; color: #5a4a2a; line-height: 1.6; }
    .footer { padding: 20px 40px; background: #eef1ef; border-top: 1px solid #d8ded9; font-size: .78rem; color: #6a7672; display: flex; flex-wrap: wrap; justify-content: space-between; gap: 8px; }
    @media print { body { background: #fff; padding: 0; } .page { box-shadow: none; border: none; border-radius: 0; } }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <h1>${COMPANY.legalName}</h1>
      <div class="service">${COMPANY.serviceName}</div>
      <div class="tagline">${COMPANY.tagline}</div>
    </div>
    <div class="meta-bar">
      <div><strong>Report reference</strong>${ref}</div>
      <div><strong>Generated</strong>${fmtDate()}</div>
      <div><strong>Website</strong>${COMPANY.website}</div>
      <div><strong>Contact</strong>${COMPANY.email} · ${COMPANY.phoneDisplay}</div>
    </div>
    <div class="body">
      <h2>Parcel summary</h2>
      <table class="parcel-table">
        <tr><td>Site area</td><td>${meta.siteAreaM2.toLocaleString()} m²</td></tr>
        <tr><td>Frontage</td><td>${meta.frontageM} m</td></tr>
        <tr><td>Road width</td><td>${meta.roadWidthM} m</td></tr>
        <tr><td>Density tier</td><td>${meta.density}</td></tr>
        <tr><td>Program type</td><td>${meta.programType.replace("_", " ")}</td></tr>
        ${meta.parcelSource ? `<tr><td>Input source</td><td>${meta.parcelSource}${meta.vertexCount ? ` (${meta.vertexCount} map vertices)` : ""}</td></tr>` : ""}
        <tr><td>Regulatory basis</td><td>${COMPANY.jurisdiction}</td></tr>
      </table>
      <h2>Scenario analysis</h2>
      ${scenarioRows}
      <div class="disclaimer">
        <strong>Disclaimer:</strong> This report is generated by the AlphaGRID regulation engine for screening and planning assistance purposes only.
        Figures tagged ESTIMATE or INTERPRETED carry stated assumptions. Confirm all requirements against the current gazetted planning instrument
        before any transaction or design commitment. ${COMPANY.legalName} accepts no liability for reliance without independent verification.
      </div>
    </div>
    <div class="footer">
      <span>${COMPANY.legalName} · ${COMPANY.serviceName}</span>
      <span>${COMPANY.website} · ${COMPANY.email} · ${COMPANY.phoneDisplay}</span>
    </div>
  </div>
</body>
</html>`;
}

export function downloadReportFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadProfessionalReport(scenarios: ScenarioResult[], meta: ReportMeta, format: "html" | "txt" = "html") {
  const slug = `alphagrid-report-${meta.siteAreaM2}m2-${reportRef(meta)}`;
  if (format === "html") {
    downloadReportFile(buildReportHtml(scenarios, meta), `${slug}.html`, "text/html;charset=utf-8");
  } else {
    downloadReportFile(buildReportText(scenarios, meta), `${slug}.txt`, "text/plain;charset=utf-8");
  }
}

export function printProfessionalReport(scenarios: ScenarioResult[], meta: ReportMeta) {
  const html = buildReportHtml(scenarios, meta);
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.onload = () => {
    win.focus();
    win.print();
  };
}
